apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: web
spec:
  selector:
    app: bank-ms
  ports:
    - protocol: TCP
      port: 9001  # This should match the port your app listens on (configured in your application properties)
      targetPort: 9001
      nodePort: 32005  # Optional: Specify a specific port (30000-32767 range)
  type: NodePort  # You can change this to NodePort or LoadBalancer based on your needs