apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ms
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-ms
  template:
    metadata:
      labels:
        app: bank-ms
    spec:
      containers:
        - name: bank-ms
          image: minaouimh/ai:Bank-ms-39
          ports:
            - containerPort: 9001
          env:
            - name: CONFIG_SERVER_URI
              value: http://34.41.170.207:32002  # Set the dynamic value for config-server
      imagePullSecrets:
        - name: docker-registry-secret  # Secret for private Docker image (if needed)