apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: web
  labels:
    app: eureka-server
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32003