apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: minaouimh/ai:eureka-server-discovery-10
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: docker-registry-secret