apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: minaouimh/ai:ConfigServer-14
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: docker-registry-secret